### ISSUE TITLE
Stack: Error: Error replacing tree

### ISSUE THREAD

**Issue by FDiskas** [gregjacobs/js-to-ts-converter#12]
No mater what I do - always getting same error
```
Stack: Error: Error replacing tree: The children of the old and new trees were expected to have the same count (12:13).
```

p.s. my code has copyright comment on top of each file

**Comment by ammaraltahan** [comment]
I'm getting that too, my original code is commented with @format and @flow

**Comment by noorfathima11** [comment]
I'm getting that too.

**Comment by ammaraltahan** [comment]
Nothing to do with comments, the offending component had aggregated styles like style=[variable1, variable2, ... etc] when I removed it the conversion passed.

**Comment by gregjacobs** [comment]
Hey guys, try it now with v0.17.0. Upgraded a dependency which might fix the problem.

Otherwise, can you post the source code of the file or files that you think are causing the issue?

**Comment by ammaraltahan** [comment]
> Hey guys, try it now with v0.17.0. Upgraded a dependency which might fix the problem.

will give it a try and let you know.

**Comment by gregjacobs** [comment]
Awesome, glad to hear! 

Best,
Greg
