### ISSUE TITLE
Anyway to convert all js to ts.

### ISSUE THREAD

**Issue by chris1054** [gregjacobs/js-to-ts-converter#5]
Any method I can run once to convert all of js files in my project?

**Comment by paganaye** [comment]
The command work on a folder 
`usage: js-to-ts-converter [-h] [-v]
                          [--indentation-text {tab,twospaces,fourspaces,eightspaces}]
                          [--include INCLUDE] [--exclude EXCLUDE]
                          [--log-level {debug,verbose,info,warn,error}]
                          directory
`

**Comment by gregjacobs** [comment]
Thanks for responding @paganaye
